### ISSUE TITLE
Query batching fails

### ISSUE THREAD

**Issue by josephktcheung** [vesper-framework/vesper#22]
I'm using `apollo-link-batch-http` to batch our graphql request but Vesper fails to run batched mutations.

Reproduction branch: https://github.com/josephktcheung/typescript-advanced-example/tree/feature/batching

Steps:
1. Reuse the `typescript-advanced-example` and upgraded `vesper` to latest
2. Here's my `index.ts`:
```ts
import { bootstrap } from "vesper";
import { PostController } from "./controller/PostController";
import { Post } from "./entity/Post";
import { CategoryController } from "./controller/CategoryController";
import { Category } from "./entity/Category";
import { PostResolver } from "./resolver/PostResolver";
import { createApolloFetch } from 'apollo-fetch';

const apolloFetch = createApolloFetch({ uri: 'http://localhost:3000/graphql' });
const request = {
    "operationName": "CreateCategory",
    "query": "mutation CreateCategory {\n  categorySave(name: \"a\") {name}}\n"
};

const run = async () => {
    const single = await apolloFetch(request);
    console.log('signle request reesult: ', JSON.stringify(single, null, 2));
    const multiple = await apolloFetch([request, request]);
    console.log('multiple requests result: ', JSON.stringify(multiple, null, 2));
}

bootstrap({
    port: 3000,
    controllers: [
        PostController,
        CategoryController
    ],
    resolvers: [
        PostResolver
    ],
    entities: [
        Post,
        Category
    ],
    schemas: [__dirname + "/schema/**/*.graphql"]
}).then(() => {
    console.log("Your app is up and running on http://localhost:3000 . " +
        "You can use Playground in development mode on http://localhost:3000/playground");
    return run();
}).catch(error => {
    console.error(error.stack ? error.stack : error);
});
```
3. Console logs:
```
Your app is up and running on http://localhost:3000 . You can use Playground in development mode on http://localhost:3000/playground
signle request reesult:  {
  "data": {
    "categorySave": {
      "name": "a"
    }
  }
}
TypeError: this.connection.createQueryRunner is not a function
    at EntityPersistExecutor.<anonymous> (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:82:75)
    at step (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:32:23)
    at Object.next (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:13:53)
    at /Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:3:12)
    at /Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:76:60
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
TypeError: this.connection.createQueryRunner is not a function
    at EntityPersistExecutor.<anonymous> (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:82:75)
    at step (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:32:23)
    at Object.next (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:13:53)
    at /Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:3:12)
    at /Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:76:60
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
TypeError: this.connection.createQueryRunner is not a function
    at EntityPersistExecutor.<anonymous> (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:82:75)
    at step (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:32:23)
    at Object.next (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:13:53)
    at /Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:3:12)
    at /Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:76:60
    at <anonymous>
TypeError: this.connection.createQueryRunner is not a function
    at EntityPersistExecutor.<anonymous> (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:82:75)
    at step (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:32:23)
    at Object.next (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:13:53)
    at /Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:3:12)
    at /Users/josephcheung/workspace/zeep/repos/typescript-advanced-example/node_modules/typeorm/persistence/EntityPersistExecutor.js:76:60
    at <anonymous>
multiple requests result:  [
  {
    "data": {
      "categorySave": null
    },
    "errors": [
      {
        "message": "this.connection.createQueryRunner is not a function",
        "locations": [
          {
            "line": 2,
            "column": 3
          }
        ],
        "path": [
          "categorySave"
        ]
      }
    ]
  },
  {
    "data": {
      "categorySave": null
    },
    "errors": [
      {
        "message": "this.connection.createQueryRunner is not a function",
        "locations": [
          {
            "line": 2,
            "column": 3
          }
        ],
        "path": [
          "categorySave"
        ]
      }
    ]
  }
]
```

**Comment by josephktcheung** [comment]
Just updated my branch to switch to postgres, which gives different result.

Here is updated `index.ts`:
```ts
import { bootstrap } from "vesper";
import { PostController } from "./controller/PostController";
import { Post } from "./entity/Post";
import { CategoryController } from "./controller/CategoryController";
import { Category } from "./entity/Category";
import { PostResolver } from "./resolver/PostResolver";
import { createApolloFetch } from 'apollo-fetch';
import { getConnection } from "typeorm";

const apolloFetch = createApolloFetch({ uri: 'http://localhost:3000/graphql' });
const generateRequest = name => ({
    "operationName": "CreateCategory",
    "query": `mutation CreateCategory {\n  categorySave(name: \"${name}\") {name}}\n`
});

const run = async () => {
    const single = await apolloFetch(generateRequest('single'));
    console.log('single request result: ', JSON.stringify(single, null, 2));
    const multiple = await apolloFetch([generateRequest('multiple 1'), generateRequest('multiple 2')]);
    console.log('multiple requests result: ', JSON.stringify(multiple, null, 2));
}

const checkPersistence = async () => {
    const categoryRepository = getConnection().manager.getRepository(Category);
    const categories = await categoryRepository.find();

    console.log('categories persisted in db: ', JSON.stringify(categories, null, 2));
}

bootstrap({
    port: 3000,
    controllers: [
        PostController,
        CategoryController
    ],
    resolvers: [
        PostResolver
    ],
    entities: [
        Post,
        Category
    ],
    schemas: [__dirname + "/schema/**/*.graphql"]
}).then(() => {
    console.log("Your app is up and running on http://localhost:3000 . " +
        "You can use Playground in development mode on http://localhost:3000/playground");
    return run();
}).then(() => {
    return checkPersistence();
})
    .catch(error => {
        console.error(error.stack ? error.stack : error);
    });
```
And here's console log:

```
Your app is up and running on http://localhost:3000 . You can use Playground in development mode on http://localhost:3000/playground
single request result:  {
  "data": {
    "categorySave": {
      "name": "single"
    }
  }
}
multiple requests result:  [
  {
    "data": {
      "categorySave": {
        "name": "multiple 1"
      }
    }
  },
  {
    "data": {
      "categorySave": {
        "name": "multiple 2"
      }
    }
  }
]
categories persisted in db:  [
  {
    "id": 1,
    "name": "single"
  }
]
```

You can see that this time multiple requests result shows up, but if you run a query against the database only records in single request are persisted, which is very misleading.

**Comment by josephktcheung** [comment]
I hope Vesper can support query batching soon. Because I'm running Vesper on aws lambda, and with batching I can reduce number of times lambda get called, which means reducing our cost.

**Comment by josephktcheung** [comment]
This means if the client sends multiple mutation requests to the server at the same time the server cannot handle them at all, no matter those requests are batched or not. This is a deal breaker to me tbh. I’ll try diving into source code to find out why

**Comment by josephktcheung** [comment]
This makes me wonder if `transaction` should not be `true` by default, because setting this to `true` implies that this mutation cannot be run simultaneously, which we don't need it in most cases unless it's critical mutation like charging customer. By making user marking `transaction` to `true` by themselves would make it clear for us to know which mutation is mission critical. What do you think @pleerock ?
